#!/usr/bin/with-contenv bash
# shellcheck shell=bash

#Check to make sure the subdomain and token are set
if [ -z "${SUBDOMAINS}" ] || [ -z "${TOKEN}" ]; then
    echo "Please pass both your subdomain(s) and token as environment variables in your docker run command. See the readme for more details."
    sleep infinity
fi

#Check if dynu configurations are set
if [ -z "${DYNU_PASS}" ] && [ -n "${DYNU_PLAINTEXT}" ] ; then
    DYNU_PASS=$(echo -n "${DYNU_PLAINTEXT}" | md5sum | cut -d ' ' -f 1)
fi

if [ -z "${DYNU_HOST}" ] || [ -z "${DYNU_PASS}" ]; then
    echo "Dynu configurations are not set. Only DuckDNS will be supported."
fi

# permissions
lsiown -R abc:abc \
    /app \
    /config

# run initial IP update
exec \
    s6-setuidgid abc /app/duck.sh
