name: Publish to Docker Hub

on:
  push:
    branches:
      - master

env:
  DOCKER_IMAGE_NAME: vttc08/docker-duckdns-dynu
  PLATFORMS: linux/amd64,linux/arm64/v8

jobs:
    build:
        name: Build Image
        runs-on: ubuntu-latest
        steps:
            - name: Docker meta
              id: meta
              uses: docker/metadata-action@v5
              with:
                # list of Docker images to use as base name for tags
                images: |
                  vttc08/docker-duckdns-dynu         
                # generate Docker tags based on the following events/attributes
                tags: |
                  type=schedule
                  type=ref,event=branch
                  type=ref,event=pr
                  type=semver,pattern={{version}}
                  type=semver,pattern={{major}}.{{minor}}
                  type=semver,pattern={{major}}
                  type=sha
                flavor: |
                  latest=true

            - name: Setup QEMU
              uses: docker/setup-qemu-action@v2
              with:
                platforms: arm,arm64,ppc64le,mips64,s390x

            - name: Setup Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Login to DockerHub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Get timestamp
              run: |
                echo "NOW=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV

            - name: Build and push
              uses: docker/build-push-action@v4
              with:
                platforms: ${{ env.PLATFORMS }}
                tags: ${{ steps.meta.outputs.tags }}
                push: true
                build-args: |
                    BUILD_DATE=${{ env.NOW }}
                    VERSION=${{ github.sha }}
                    DUCKDNS_VERSION=1.1.1
                    
            - name: checkout
              uses: actions/checkout@v2

            - name: Dockerhub description
              uses: peter-evans/dockerhub-description@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
                repository: ${{ env.DOCKER_IMAGE_NAME }}
